package Testing.Test;

public enum DesignPatterns {
    
    BUILDER_PATTERN,
    DECORATIVE_PATTERN,
    SINGLETON_PATTERN,
    FACTORY_PATTERN,
    STRATEGY_PATTERN,
    OBSERVER_PATTERN,

    COMMAND_PATTERN,
    CHAIN_OF_RESPONSIBILITY_PATTERN
}
